apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend
          image: gcr.io/my-blog-454607/frontend-app:latest  # Cập nhật với image mới
          ports:
            - containerPort: 80  # Sử dụng port 80 của Nginx thay vì 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 80  # Chuyển sang port 80 của Nginx
