apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend
          image: gcr.io/my-blog-454607/frontend-app:latest  # Cập nhật với image mới
          ports:
            - containerPort: 80  # Sử dụng port 80 của Nginx thay vì 8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf  # Mount tệp nginx.conf từ ConfigMap vào /etc/nginx/nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf  # Tên của ConfigMap mà bạn đã tạo trước đó
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 80  # Chuyển sang port 80 của Nginx
